### PR TITLE
Accept TLS certificates for Chef server #minor

### PR DESCRIPTION
**Pull request by limitusus**
For private (self-signed) chef-server, I want to validate server certificate, not skipping validation.

### CODE REVIEW

**Comment by MarkGibbons** [comment]
Thanks for the PR.  I'll look it over shortly.

**Comment by MarkGibbons** [comment]
Could you add a test that shows how to use the certs?  Do you have any idea if we could set this up to work with the example chef server and its Inspec tests?

**Comment by limitusus** [comment]
@MarkGibbons 
I wrote a test for TLS certificate validation. It explains how the private cert works.
This test I think is enough for the new option.

For the example chef server test, the test should run goiardi, which requires much more effort than this simple case.

**Comment by MarkGibbons** [comment]
thank you again.  I'll check out the new test. Much appreciated.

**Comment by MarkGibbons** [comment]
Adding some tests. Will merge once they work.

**Comment by MarkGibbons** [comment]
Included in #156

**Pull request closed without merging**
