### PR TITLE
#minor - Add a GetAttribute function in the Node struct

### PR DESCRIPTION
**Pull request by rvrangel**
This will add a new function to the `Node` struct that allows you to get the attribute from a particular path, e.g.:

```
node.GetAttribute("ec2") -> map[string]interface{}{"instance_id": "i-0a39517e4xxxxxxxx"}, nil

node.GetAttribute("ec2", "instance_id") -> "i-0a39517e4xxxxxxxx", nil

node.GetAttribute() -> nil, ErrNoPathProvided
```

### CODE REVIEW

**Comment by MarkGibbons** [comment]
Thank you.  I'll get to this today or tomorrow.  Thanks for adding tests.

**Review by MarkGibbons — COMMENTED** [review]
Minor wording suggestion and a typo.  Looks good.

**Comment by MarkGibbons** [comment]
Could you fix the minor things I noted?

**Comment by rvrangel** [comment]
Thanks for reviewing it :smile:

**Pull request merged**
