### PR TITLE
Add endpoint to get all recipes from all cookbooks

### PR DESCRIPTION
**Pull request by svanharmelen**
This is an existing Chef Server API endpoint, but it was not yet available using this package...

[Review on Reviewable](https://reviewable.io/reviews/go-chef/chef/73)

### CODE REVIEW

**Comment by spheromak** [comment]
@svanharmelen awesome thanks for the improvement. can you add an accompanying test as well before we merge.

**Comment by svanharmelen** [comment]
Yeah sure, I was just thinking about that myself :grinning:

**Comment by svanharmelen** [comment]
@spheromak test added and passed...

**Comment by svanharmelen** [comment]
Thanks :+1:

**Pull request merged**
