### PR TITLE
fix the issue76 missing version from the cookbook delete path

### PR DESCRIPTION
**Pull request by aruntomar**
issue fixed and tested in my code. kindly review and merge it.

---
This change is [Reviewable](https://reviewable.io/reviews/go-chef/chef/77)

### CODE REVIEW

**Comment by fujin** [comment]
Seems OK, can you update the tests here? https://github.com/go-chef/chef/blob/master/cookbook_test.go#L66-L82

**Comment by aruntomar** [comment]
Sure. Although, i’ve not written much test cases in golang, i’ll give it a try.

**Comment by aruntomar** [comment]
Hi AJ,

when i run “go test” on your repo, it runs fine. but when i run the same “go test” on the my repo, that i forked on github from your repo, for enhancing and sending the pull request, then all the test fails. It seems either all the results that are returned in the test cases are either blank or nil. 

Please help me fix it, so that i can proceed with the test cases. 

Thanks,
Arun.

**Comment by aruntomar** [comment]
hi guys. i've fixed the issue that i was facing while running the test and have updated the cookbook_test.go file as well. kindly review and merge the changes if everything is ok.

**Comment by aruntomar** [comment]
I see that there is something called wercker being used and seems like it's CI and it's failing. but if i run "go test" or "go test -v" manually, it's passing all the test. hence submitted the pull request.

**Comment by spheromak** [comment]
@aruntomar thnx for the PR, the failure in CI is due to a bug in coverage reporting setup there. I will try to resolve that, but the PR itself is testing fine.

**Pull request merged**
