### PR TITLE
Add support for PKCS8 auth keys

### PR DESCRIPTION
**Pull request by svagner**
Chef supports auth with PKCS8 keys. This PR adds support for it and prevents error

```
x509: failed to parse private key (use ParsePKCS8PrivateKey instead for this key format)
```

### CODE REVIEW

**Comment by MarkGibbons** [comment]
Thank you. I'll try to look at it over the weekend.

**Comment by svagner** [comment]
> Thank you. I'll try to look at it over the weekend.

Hi Mark. Did you have a chance to take a look at these changes? Thanks!

**Comment by MarkGibbons** [comment]
I looked them over.  Mostly good.  It's a pretty big pull request and will take a while to digest.  I'd like to see integration tests too.  Those will take me some time to write.  Depending on my day job and life in general I think about a week.

**Comment by MarkGibbons** [comment]
Thanks for this one.  Really nice code. Appreciate it.

**Comment by svagner** [comment]
Thanks for merging it!:)

**Pull request merged**
