### PR TITLE
Add env_run_lists attribute in role detail

### PR DESCRIPTION
**Pull request by vsingh-msys**
- Add `env_run_lists` in Role struct.

Fixes: https://github.com/go-chef/chef/issues/177

Signed-off-by: Vivek Singh <vivek.singh@msystechnologies.com>

### CODE REVIEW

**Comment by MarkGibbons** [comment]
Thank you for the PR.

**Comment by MarkGibbons** [comment]
I'll get this merged.  It's the type of thing that's very hard to find so it's very much appreciated.
The merge will be next week or the week after.  I've got a rule for myself that changes have to actually work in tests against a real chef server (see examples and chefapi_test cookbook). We don't have any roles or environment tests created yet and setting that up takes most of a day for each type of entity.

**Comment by vsingh-msys** [comment]
Sure, thanks

**Comment by vsingh-msys** [comment]
@MarkGibbons Could you please let me know the steps that you follow for testing and development purposes?

**Comment by MarkGibbons** [comment]
I'll add some doc about testing and development.  I'll take the request as a really good suggestion.
Thanks

Basic ideas for adding an endpoint, assume you will repeat this process and each step multiple times:

Design the data structures for a new end point

Create go tests for each func.

Write the go code.
  
Add examples to exercise the functions in the chefapi_examples cookbook.
- Create go code to call the functions. See the files in go-chef/chef/examples/cmd. Many times extra setup is required. 
- Create a shell script to call the go code.  See the files in go-chef/chef/examples/bin.
- Write Inspec tests to verify the output.  Be aware that go map output does not alway have consistent ordering. The matching regex structures are rarely fun to write.
- Commit the go-chef/chef (api client go code at least) changes to a branch and push to GitHub.   The chefapi.rb recipe would need to be updated to pull from the correct repo.
- kitchen converge. - installs the code, spins up a chef server to test against
- kitchen login - run the /bin commands and iterate on fixing the code. Both cmd code and chef client code. kitchen converge will install cmd and bin file changes without committing and pushing to GitHub. Changes to the chef api client code need to be committed, pushed and kitchen converge run again to get the changes installed.
- While logged in to the virtual box image try adding "-tags" debug  the bin command.  Example
   go run -tags debug ${BASE}/../cmd/client/clients.go ${CHEFUSER} ${KEYFILE} ${CHEFORGANIZATIONURL} ${SSLBYPASS} will produce output that shows the real request body returned from the chef server.  Note what you passed in and what you got back. Send updates for the documentation to https://github.com/chef/chef-web-docs
- After things work ok. Create an inspec test for the endpoint that calls the bin command for the endpoint.  Run kitchen verify to run the full set of integration tests.

Run cookstyle -a in the go-chef/chef/examples/chefapi_examples directory

Run go fmt in the go-chef/chef directory

See if any documentation needs to be updated, check to see if any of the scattered TODOs are now now.  

Commit and PR

**Comment by MarkGibbons** [comment]
This PR will be merged as part of #180

**Pull request closed without merging**
