### PR TITLE
Add Environments#ListRecipes API

### PR DESCRIPTION
**Pull request by vsingh-msys**
- Add missing environments list recipes API https://docs.chef.io/api_chef_server/#get-33

### CODE REVIEW

**Comment by MarkGibbons** [comment]
Thank you.

**Comment by vsingh-msys** [comment]
@MarkGibbons could you please fix the test case and ship this code?
Thanks!

**Comment by MarkGibbons** [comment]
I plan. to look at OSS stuff this weekend. 

By test case to fix I assume you mean the ci/circleci test.  I'll take a look.  Anything else?

I see you have unit tests, but not integration tests.  If I run into any issues with the integration tests it could take longer.  Cheers and thanks for the PR.

**Comment by vsingh-msys** [comment]
Yeah, circleci is faining somehow, nothing else all fine I guess, thanks!

**Comment by MarkGibbons** [comment]
The PR looks good. I'm working on integration testing.  I have no idea what's going on with circleci that may take some time, but isn't import in terms of getting this merged.

**Comment by vsingh-msys** [comment]
@MarkGibbons could you please board this PR? Thanks!

**Comment by MarkGibbons** [comment]
merge?  I hope to get to it.  There is quite a bit of work to do to get it into shape.

**Comment by vsingh-msys** [comment]
Yes, okay no issues just wanted to get this merge.

**Comment by MarkGibbons** [comment]
Looks like I've got an hour.  Let's see if I can knock out the integration tests.

**Comment by MarkGibbons** [comment]
Probably have to be the weekend.  I found too many problems in the environment code.  Your stuff works, creating integration tests for the new function doesn't work.

**Comment by vsingh-msys** [comment]
Okay sure thanks!

**Pull request merged**
