### PR TITLE
change SearchResult to use json.RawMessage instead of interface{}

### LINKED ISSUE #213: SearchResult#Rows should be an array of json.RawMessage and not empty interface
We have a struct defined as:
```
type SearchResult struct {
	Total int
	Start int
	Rows  []interface{}
}
```

Here, `Rows` is an array of the empty `interface{}`. But we know that whatever item the server returns as the "rows", must be valid json. So we can make it stricter by specifying the type as `json.RawMessage`.
```
type SearchResult struct {
	Total int
	Start int
	Rows  []json.RawMessage
}
```

This way, it is also made faster and the caller can then cast the individual elements to whichever index type they've queried, instead of having to deal with a `map[string]interface{}`.

### PR DESCRIPTION
**Pull request by satyanash**
fixes #213

### CODE REVIEW

**Comment by MarkGibbons** [comment]
That's a breaking change. Getting that in needs a little thought. I've also been really busy for the last month.

**Comment by MarkGibbons** [comment]
The integration tests are broken as expected.  Still looking at options.

**Comment by satyanash** [comment]
> integration tests are broken as expected

I'm assuming these are not public? Because the GitHub CI checks seem to have passed.

**Comment by MarkGibbons** [comment]
The tests are public, they just don't run well enough yet to make them part of the pipeline.  There's a cookbook in the test-chef-server directory that has examples  using all of the api calls and server spec tests of the results.  The cookbook spins up a chef server.



I'm torn between providing the output the way your PR does, providing alternate client calls or providing a way to convert the []interface output to []RawMessage.  People do use the search capability and breaking the interface would cause some problems.  I started a new job and do not a lot of time to work on it right now. The PR is a really good idea. Thanks

**Comment by MarkGibbons** [comment]
@satyanash  Could you look at #215 and see if that would work for you?  

I looked at adding another function (instead of this PR that replaces the existing function) to return json.RawMessage output directly in a SearchJResult structure.  I don't see how to do it without duplicating a lot of hard to maintain code.

I don't want to break the current search interface. People do use that interface.

func JsonResult converts the interface{} rows to json.RawMessage.  I don't really like it but I'm having a hard time seeing something else compatible. 

thanks,
  Mark

**Comment by MarkGibbons** [comment]
Included in #239

**Pull request closed without merging**
